config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'mybookings', to: 'pages#mybookings'
  resources :pages, only: [:create]
  get 'mydashboard', to: 'pages#mydashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :new, :create]

  resources :trainers, only: [:index, :show, :new, :create, :edit] do
    resources :services, only: [:index, :show, :new, :create, :edit, :destroy] do
      resources :bookings, only: [:index, :show, :new, :create]
    end
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :trainer
  has_many :bookings
  has_many :reviews, through: :bookings
  has_one_attached :photo
  after_create :generate_sku
  validates :photo, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  monetize :price_cents

  def generate_sku
    self.update(sku: "product_#{id}")
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @trainer = Trainer.find(params[:trainer_id])
    @services = @trainer.services
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @trainer = Trainer.find(params[:trainer_id])
    @service = Service.new
  end

  def create
    @trainer = Trainer.find(params[:trainer_id])
    @service = Service.new(service_params)
    @service.service_type = params[:service_type]
    @service.trainer = @trainer
    if @service.save
      redirect_to trainer_path(@trainer), notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to trainer_path(@service.trainer), notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to trainer_service_path, notice: 'Service was successfully destroyed.'
  end

  private

  def service_params
    params.require(:service).permit(:trainer_id, :description, :service_type, :address, :sport, :price, :title, :duration, :photo)
  end
end

app/views/services/index.html.erb
<div class="container">
      <% @services.each_with_index do |service, i|  %>
        <div class="card-product">
          <img src="https://jumpn-app.com/assets/our-vision.png" />
              <div class="card-product-infos">
                  <%= service.trainer.user.first_name %>
                  <%= service.description %>
                  <%= service.sport %>
                  <%= humanized_money_with_symbol(service.price) %>
        </div>
  </div>
  <% end %>
</div>

app/views/services/new.html.erb
  <div class="container" data-controller="trainers-form">
    <div class="form-wrapper d-flex flex-column align-items-center w-100 py-5 my-5">
      <h1>New Service</h1>
      <%= form_with(model: @service, url: trainer_services_path(@trainer)) do |form| %>
        <div class="service-type-container">
          <input type="radio" name="service_type" id="training-plan-switch" value="Training Plan" class="switch-input" checked data-action="click->trainers-form#toggleSession">
          <label class="switch-label" for="training-plan-switch"></label>
          <label for="training-plan-switch" class="service-type-label">Training Plan</label>
          <input type="radio" name="service_type" id="session-switch" value="Session" class="switch-input" data-action="click->trainers-form#toggleSession">
          <label class="switch-label" for="session-switch"></label>
          <label for="session-switch" class="service-type-label">Session</label>
        </div>

        <div class="form-fields training-plan-fields">
        </div>

          <div>
            <%= form.label :title, class: "form-label" %>
            <%= form.text_area :title, class: "form-field" %>
          </div>

          <div>
            <%= form.label :description, class: "form-label" %>
            <%= form.text_area :description, class: "form-field" %>
          </div>

          <div>
            <%= form.label :sport, class: "form-label" %>
            <%= form.select :sport, options_for_select(['Running', 'Cycling', 'Yoga', 'Gym', 'Tennis']), prompt: 'Select sport', class: "form-field" %>
          </div>

          <div class="form-fields session-fields d-none" data-trainers-form-target="form">
            <div>
              <%= form.label :address, class: "form-label" %>
              <%= form.text_field :address, class: "form-field" %>
            </div>

            <div>
              <%= form.label :duration, "Duration (hours)", class: "form-label" %>
              <%= form.number_field :duration, class: "form-field" %>
            </div>
          </div>

          <div>
            <%= form.label :price, class: "form-label" %>
            <%= form.number_field :price, class: "form-field" %>
          </div>

          <div>
            <%= form.label :photo, class: "form-label" %>
            <%= form.file_field :photo, class: "form-field" %>
          </div>

        <div>
          <%= form.submit "Create Service", class: "submit-button" %>
        </div>
      <% end %>
    </div>
   </div>

app/views/services/show.html.erb
<h1>Service Details</h1>

<p><strong>Trainer:</strong> <%= @service.trainer_id %></p>
<p><strong>Description:</strong> <%= @service.description %></p>
<p><strong>Service Type:</strong> <%= @service.service_type %></p>
<p><strong>Address:</strong> <%= @service.address %></p>
<p><strong>Sport:</strong> <%= @service.sport %></p>
<p><strong>Price:</strong> <%= humanized_money_with_symbol(@service.price) %></p>