config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'mybookings', to: 'pages#mybookings'
  resources :pages, only: [:create]
  get 'mydashboard', to: 'pages#mydashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :new, :create]

  resources :trainers, only: [:index, :show, :new, :create, :edit] do
    resources :services, only: [:index, :show, :new, :create, :edit, :destroy] do
      resources :bookings, only: [:index, :show, :new, :create]
    end
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_one :review
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @bookings = Booking.all
  end

  def new
    @trainer = Trainer.find(params[:trainer_id])
    @service = Service.find(params[:service_id])
    @booking = Booking.new
  end

  def create
    @trainer = Trainer.find(params[:trainer_id])
    @service = Service.find(params[:service_id])
    @booking = Booking.new(booking_params)
    @booking.service = @service
    @booking.user = current_user
    if @booking.save!
      redirect_to mybookings_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to mybookings_path
  end

  def show
    @user = User.find(params[:user_id])
    @trainer = Trainer.find(params[:trainer_id])
    @service = Service.find(params[:service_id])
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:service_id, :user_id, :status, :start_time, :end_time)
  end
end

app/views/bookings/_booking.html.erb
<div class="card-product d-flex justify-content-around" >
  <% if booking.service.service_type == "Session" %>
    <div class="date"><%=booking.start_time.strftime("%a %d").capitalize %> </div>

    <div class="card-product-infos">
      <p>🕓 <%= booking.start_time.strftime("%-k:%M")%> </p>
      <p>📍 <%= booking.service.address %></p>
    </div>

    <div class='d-flex'>
      <p><%= booking.service.sport %></p>
      <%= cl_image_tag booking.service.photo.key, alt: "athlete", class: "avatar" %>
    </div>
    <%= link_to "cancel", booking_path(booking), class: "btn-cancel", data: {turbo_method: :delete, turbo_confirm: "are you sure?"}%>


    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal1">
      Leave a review
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><%= booking.service.title %></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <%= simple_form_for [booking, @review] do |form| %>
            <div class="modal-body">
              <div class="mb-3">
                <%= form.label :rating, class: "form-label" %>
                <%= form.number_field :rating, class: "form-control", min: 0, max: 5 %>
              </div>
              <div class="mb-3">
                <%= form.label :comment, class: "form-label" %>
                <%= form.text_area :comment, class: "form-control", rows: 3 %>
              </div>
            </div>
            <div class="modal-footer">
              <%= form.submit "Review", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  <% else %>

    <div class="title"><%=booking.service.title %></div>
    <div class="card-product-infos-training">
      <p> <%= booking.service.description%> </p>
    </div>

    <div class='d-flex'>
      <p><%= booking.service.sport %></p>
      <%= cl_image_tag booking.service.photo.key, alt: "athlete", class: "avatar" %>
    </div>
    <%= link_to "cancel", booking_path(booking), class: "btn-cancel", data: {turbo_method: :delete, turbo_confirm: "are you sure?"}%>
  <% end %>
</div>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>User</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.user.each do |booking| %>
      <tr>
        <td><%= booking.service_id %></td>
        <td><%= booking.user_id %></td>
        <td><%= booking.start_time %></td>
        <td><%= booking.end_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<div class = "container mt-5 mb-5">
  <h1>bookings</h1>


  <%= form_with(model: @booking, url: trainer_service_bookings_path(@trainer, @service)) do |form| %>

    <div>
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>

    <div>
      <%= form.label :end_time %>
      <%= form.datetime_select :end_time %>
    </div>

    <div>
      <%= form.submit "Create Booking" %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p><strong>Service:</strong> <%= @booking.service_id %></p>
<p><strong>User:</strong> <%= @booking.user_id %></p>
<%# <p><strong>Status:</strong> <%= @booking.status %>
<p><strong>Start Time:</strong> <%= @booking.start_time %></p>
<p><strong>End Time:</strong> <%= @booking.end_time %></p>