config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'mybookings', to: 'pages#mybookings'
  resources :pages, only: [:create]
  get 'mydashboard', to: 'pages#mydashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :new, :create]

  resources :trainers, only: [:index, :show, :new, :create, :edit] do
    resources :services, only: [:index, :show, :new, :create, :edit, :destroy] do
      resources :bookings, only: [:index, :show, :new, :create]
    end
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" background-color=$red>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made with <i class="fas fa-heart"></i> by Louis, Linda, Javier & Kevin
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "full-logo.png" %>
    <% end %>

<% if controller_name == 'trainers' && action_name == 'index' %>
  <%= form_with url: trainers_path, method: :get, class: "search-form" do |f| %>
     <%= f.text_field :query,
      value: params[:query],
      class: "query-field",
      placeholder: "Location" %>
      <%= f.select(:sport, options_for_select(Trainer.all.map(&:sports).reject(&:blank?).map { |sport| sport.split(",") }.flatten.uniq, selected: params[:sport]), { :include_blank => 'sport'}, { class: "filter-field" }) %>
      <%#= f.range_field :price, in: (Service.all.map(&:price).sort[0]..Service.all.map(&:price).sort[-1]), value: params[:price].to_i %>
      <%#= f.select(:price, options_for_select(Trainer.all.map(&:services).flatten.map(&:price).uniq, selected: params[:price]), { :include_blank => 'price'}, { class: "filter-field" }) %>

     <button class='btn btn-search' type="submit">
      <i class="fa-solid fa-magnifying-glass"></i>
     </button>
   <% end %>
 <% end %>

    <button class="navbar-toggler" type="button" color= data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <% if current_user.trainer  %>
              <%= link_to "Add an activity", new_trainer_service_path(current_user.trainer), class: "nav-link" %>
              <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "jumpn-default-profile-img.png", class: "avatar", alt: "dropdown menu" %>
              <% end %>

            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My Trainer Profile", trainer_path(current_user.trainer), class: "dropdown-item" %>
                <%= link_to "My Dashboard", mydashboard_path, class: "dropdown-item" %>
                <%= link_to "My Bookings", mybookings_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else%>
              <%= link_to "Become a Trainer", new_trainer_path, class: "nav-link" %>
            <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "jumpn-default-profile-img.png", class: "avatar", alt: "dropdown menu" %>
            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

                <%= link_to "My Bookings", mybookings_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path(@service, @trainer), data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
            <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>