config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'mybookings', to: 'pages#mybookings'
  resources :pages, only: [:create]
  get 'mydashboard', to: 'pages#mydashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :new, :create]

  resources :trainers, only: [:index, :show, :new, :create, :edit] do
    resources :services, only: [:index, :show, :new, :create, :edit, :destroy] do
      resources :bookings, only: [:index, :show, :new, :create]
    end
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  belongs_to :user
  has_many :services

    include PgSearch::Model
    pg_search_scope :search_by_sports_and_address_and_description,
    against: [ :sports, :description ],
    associated_against: {
      services: [ :description, :address]
    },
    using: {
    tsearch: { prefix: true }
    }
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:query].present?
      @query = true
      sql_query = "sports ILIKE :query"
      # sql_query = "sports ILIKE :query OR synopsis ILIKE :query"
      @trainers = Trainer.search_by_sports_and_address_and_description(params[:query])
      @services = Service.all
      @booking = Booking.new
      @markers = @services.geocoded.map do |service|
        {
          lat: service.latitude,
          lng: service.longitude,
          info_window: render_to_string(partial: "popup", locals: { service: service, trainer: service.trainer })
          # marker_html: render_to_string(partial: "marker", locals: {service: service})
        }
      end
    else
      @trainers = Trainer.all
    end
    @trainers = @trainers.select { |trainer| trainer.sports.include?(params[:sport]) } if params[:sport].present?
    # @trainers = @trainers.select { |trainer| trainer.services.select { |service| service.price <= params[:price].to_i }.length > 0 } if params[:price].present?
  end

  def show
    @booking = Booking.new
    @trainer = Trainer.find(params[:id])
    @services = Service.where(trainer: @trainer)
    @reviews = @services.map(&:reviews).flatten + @services.map(&:reviews).flatten + @services.map(&:reviews).flatten
    @markers = @services.geocoded.map do |service|
      {
        lat: service.latitude,
        lng: service.longitude
      }
    end
  end

  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(trainer_params)
    @trainer.sports = params[:trainer][:sports].reject(&:blank?).join(",")
    @trainer.user = current_user
    if @trainer.save
      current_user.update(istrainer: true)
      redirect_to trainer_path(@trainer), notice: 'Congrats, Your are a trainer!.'
    else
      render :new
    end
  end

  def edit
    @trainer = Trainer.find(params[:id])
  end

  def update
    if @trainer.update(trainer_params)
      redirect_to trainer_path(@trainer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def trainer_params
    params.require(:trainer).permit(:description, :user_id, sports: [])
  end


end

app/views/trainers/_popup.html.erb
<div class="popup-container">
  <h2> <%= service.title %></h2>
  <h3> <%= service.sport %> - <%= service.price %> £ </h3>
  <p class="description"><%= service.description %></p>
  <h1> <%= service.address %> </h1>
  <div type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal"> <%= link_to "show trainer", trainer_path(trainer) %></div>
</div>

app/views/trainers/index.html.erb
<div class="container pb-5">
  <% if @query %>
    <div class="main-container">
      <div class="cards-query">
        <% @trainers.each_with_index do |trainer, i| %>
          <%= link_to trainer_path(trainer), class: "text-decoration-none mt-4 text-dark" do %>
            <div class="card-trip">
              <% if trainer.user.photo.attached? %>
                <%= cl_image_tag trainer.user.photo.key %>
              <% else %>
                <%= image_tag "jumpn-default-profile-img.png" %>
              <% end %>
              <div class="card-trip-infos">
                <div>
                  <h2 class="mb-3"><%= trainer.user.first_name %> <%= trainer.user.last_name %></h2>
                  <p><%= trainer.sports.split(',').join(", ") %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div style="width: 50%; height: 600px;"
        class="mt-4"
        id="map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  <% else %>
    <div class="cards">
      <% @trainers.each_with_index do |trainer, i| %>
        <%= link_to trainer_path(trainer), class: "text-decoration-none mt-4 text-dark" do %>
          <div class="card-trip">
            <% if trainer.user.photo.attached? %>
              <%= cl_image_tag trainer.user.photo.key %>
            <% else %>
              <%= image_tag "jumpn-default-profile-img.png" %>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2 class="mb-3"><%= trainer.user.first_name %> <%= trainer.user.last_name %></h2>
                <p><%= trainer.sports.split(',').join(", ") %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/trainers/new.html.erb
<div class = container>
  <h1 class="newTrainerTitle">New Trainer</h1>

  <%= simple_form_for @trainer do |form| %>
    <div class="sportsField">
      <%= form.input :sports, as: :check_boxes, collection: ['Running', 'Cycling', 'Yoga', 'Gym', 'Tennis'] %>
    </div>
    <div class="descriptionField">
      <%= form.input :description %>
    </div>
    <div class="submitTrainer">
      <%= form.submit  "Become a Trainer" %>
    </div>
  <% end %>

</div>

app/views/trainers/show.html.erb
<div class="trainer-section" data-controller="trainers-form">
  <div class="container trainer-container">
    <% if current_user&.trainer %>
      <div class="profile-banner d-flex pt-4">
        <% if @trainer.user.photo.attached? %>
          <%= cl_image_tag @trainer.user.photo.key, class: "card-image me-4" %>
        <% else %>
          <%= image_tag "jumpn-default-profile-img.png", class: "card-image me-4" %>
        <% end %>

        <div class="trainer-details1">
          <h1 class="mb-3"><strong> <%= @trainer.user.first_name %> <%= @trainer.user.last_name %></strong></h1>
          <p><strong>Sports:</strong> <%= @trainer.sports.split(',').join(", ") %></p>
          <p class="mr-5"><strong></strong> <%= @trainer.description %></p>
          <% if @trainer.user == current_user %>
            <%= link_to "Add an activity", new_trainer_service_path(@trainer) , class: "btn btn-primary mr-2" %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="profile-banner d-flex pt-4">
        <% if @trainer.user.photo.attached? %>
          <%= cl_image_tag @trainer.user.photo.key, class: "card-image me-4" %>
        <% else %>
          <%= image_tag "jumpn-default-profile-img.png", class: "card-image me-4" %>
        <% end %>
        <div class="trainer-details1">
          <div class="d-flex justify-content-between align-items-end">
            <h1 class="mb-3"><strong> <%= @trainer.user.first_name %> <%= @trainer.user.last_name %></strong></h1>
            <%# RATING %>
            <% rating = 0.0 %>
            <% count = 0 %>
            <% @trainer.services.each do |service| %>
              <% if service.reviews.any? %>
              <% rating += service.reviews.map(&:rating).sum %>
              <% count += service.reviews.length %>
                <%#= (service.reviews.map(&:rating).sum)/service.reviews.length %>
              <% end %>
            <% end %>
            <div class="rating-container pb-4">
              <%# <p><strong>Rating:</strong></p> %>
              <div class="star-rating">
                <span class="star">&#9733;</span>
                <span class="rating-number"><%= (rating / count).round(1) %></span>
              </div>
            </div>

            <%# RATING %>
          </div>
          <p><strong>Sports:</strong> <%= @trainer.sports.split(',').join(", ") %></p>
          <div class="mt-2 mb-2" style="font-size: 30px;">
            <i class="fa-brands fa-instagram"></i>
            <i class="fa-brands fa-twitter"></i>
            <i class="fa-brands fa-facebook"></i>
          </div>
            <p class="mr-5"><strong></strong> <%= @trainer.description %></p>
            <p class="mr-5"><strong></strong> <%= @trainer.services.first.address %></p>

        </div>
      </div>
    <% end %>
  </div>

</div>
<div class="bg-white p-4">
  <% if current_user&.trainer %>


    <div class="container trainer-container">

        <table class="services-table">
          <thead>
            <tr>
              <th>Type of service</th>
              <th>Price</th>
              <th>Sport</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <% @trainer.services.each do |service| %>
              <tr>
                <td><%= service.service_type %></td>
                <td><%= humanized_money_with_symbol(service.price) %></td>
                <td><%= service.sport %></td>
                <td><%= service.description %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    <div class="container trainer-container">
      <div class="services-section">
        <div class="w-25 me-5">
          <h2>Training Plans</h2>
          <div class="training-plan-category">
            <% @trainer.services.each do |service| %>
              <% if service.service_type == "Training Plan" %>
                <div class="service-card">
                  <div class="service-card-infos">
                    <h6><%= service.title %></h6>
                    <%= cl_image_tag service.photo.key, class: "card-image mb-3", style: "height: 200px; width: 100%; object-fit: cover;" %>
                    <p><strong>Price:</strong> <%= humanized_money_with_symbol(service.price) %></p>
                    <p><strong>Sport:</strong> <%= service.sport %></p>
                    <%# <p><%= service.description %></p>
                    <!-- Button trigger modal -->

                        <button type="button" class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#exampleModal_<%= service.id %>">
                          More info </button>
                          <!-- Modal -->
                        <div class="modal fade" id="exampleModal_<%= service.id %>" tabindex="-1" aria-labelledby="exampleModal_<%= service.id %>Label" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">

                                <h5 class="modal-title" id="exampleModal_<%= service.id %>Label"><%= service.title %></h5>

                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="col-12">
                              <h5>Description</h5>
                              <p><%= service.description %></p>
                            </div>

                                <%= simple_form_for [@trainer, service, @booking] do |form| %>
                                  <%= form.hidden_field :start_time, :value => Date.today %>
                                  <div class="d-flex align-items-center justify-content-between mb-4" style="width: 307.875px;">
                                    <p><strong>Price:</strong> <%= service.price %></p>

                                  </div>
                                <% end %>
                                  <%= form_with url: orders_path do %>
                                    <%= hidden_field_tag 'service_id', service.id %>
                                    <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
                                  <% end %>
                            </div>
                          </div>
                        </div>


                  </div>

                </div>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="service-category w-75">
          <h2>Sessions</h2>
          <div class="row align-items-start">
            <% @trainer.services.each do |service| %>
              <% if service.service_type == "Session" %>
                <div class="col-4">
                  <div class="service-card">
                    <h6><%= service.title %></h6>
                    <%= cl_image_tag service.photo.key, class: "card-image me-4" %>
                    <div class="service-card-infos">
                      <p><strong>Price:</strong> <%= humanized_money_with_symbol(service.price) %></p>
                      <p><strong>Sport:</strong> <%= service.sport %></p>
                      <!-- Button trigger modal -->
                      <div class="d-flex justify-content-center">
                        <button type="button" class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#exampleModal<%= service.id %>">
                          More info
                        </button>
                      </div>

                                    <!-- Modal -->
                <div class="modal fade" id="exampleModal<%= service.id %>" tabindex="-1" aria-labelledby="exampleModal<%= service.id %>Label" aria-hidden="true">
                  <div class="modal-dialog modal-lg" id="sessions-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModal<%= service.id %>Label"><%= service.title %></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body" id="sessions-body">
                        <div class="row">
                          <div class="col-12">
                            <h5>Description</h5>
                            <p><%= service.description %></p>
                          </div>
                          <div class="col-md-6">
                            <h5>Location</h5>
                            <p class="mb-3"><%= service.address %></p>
                            <div style="width: 100%; height: 400px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
                          </div>
                          <div class="col-md-6">
                            <div class="d-block no-border">
                              <div>
                              <h5>Start time</h5>
                              <p class="mb-3">Training Duration: <%= service.duration %> hours</p>
                              <%= simple_form_for Order.new do |form| %>
                              <%#= simple_form_for [@trainer, service, @booking] do |form| %>
                                <%= form.input :start_time,
                                as: :string,
                                label: false,
                                input_html: { data: { controller: "datepicker" }, class: "d-none", value: DateTime.now } %>
                                <div class="d-flex align-items-center justify-content-between" style="width: 307.875px;">
                                  <p><strong>Price:</strong> <%= service.price %></p>

                                </div>
                              <%# end %>
                                <%= hidden_field_tag 'service_id', service.id %>
                                <%= form.submit 'Purchase', class: 'btn btn-primary' %>
                              <% end %>
                          </div>
                              <%# <button type="button" class=""><%= link_to "Book", new_trainer_service_booking_path(@trainer, service), class: "btn" %>


                            </div>

                          </div>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>

                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
            <div>
          </div>

          <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
            <div class="carousel-inner">
            <h1>Reviews</h1>
              <% @reviews.each_slice(3).with_index do |reviews, i| %>
                <div class="carousel-item <%= 'active' if i == 0 %>">
                  <div class="row">
                    <% reviews.each do |review| %>
                      <div class="col-4">
                        <div class="review-card">
                        <div class="d-flex flex-column justify-content-center align-items-center">
                          <% if review.booking.user.photo.attached? %>
                            <%= cl_image_tag review.booking.user.photo.key, class: "" %>
                          <% else %>
                            <%= image_tag "jumpn-default-profile-img.png", class: "" %>
                          <% end %>
                          <p class="stars"><% review.rating.times do %>
                            <span class="star">&#9733;</span>
                          <% end %></p>
                        </div>
                          <p>"<%= review.comment %>"</p>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>